/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ic;

import java.awt.Image;
import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author fernanda
 */
public class Interface extends javax.swing.JFrame {
    List<String> pathlist;
    List<ImgsNText> imgsNTextlist;
    DefaultListModel dm;
    String pathString = "/home/fernanda/NetBeansProjects/IC/src/ic/images/Brodatz/";
    int position10;
    List<Image> imgList;
    
    public Interface() {
        imgList = new ArrayList<Image>();
        imgsNTextlist = new ArrayList<ImgsNText>();
        pathlist = new ArrayList<String>();
        dm=new DefaultListModel();
        initComponents();
        initList();
        
    }
    public void initList(){
    
        addtojList();
        
        position10 = 0;
        jList1.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if (!arg0.getValueIsAdjusting()) {
                  int pos = jList1.getSelectedIndex();
                  lImageSelected.setIcon(imgsNTextlist.get(pos).getImg());
                     
                }
            }
        });
    
    }
    
    
    public void addtojList(){
    
        File folder = new File(pathString);
        if(pathlist.isEmpty() == false )
        {
            System.out.println("Is not empty");
            System.out.println(pathlist);
            pathlist.clear();
        }
        for(File file : folder.listFiles()){
            pathlist.add(file.getName());
        }
       
        /*
        pathlist = Arrays.asList(folder.list(
           new FilenameFilter() {
              @Override public boolean accept(File dir, String name) {
                return name.endsWith(".gif") || name.endsWith(".jpg")  ;
              }
           }
        ));
        */
        System.out.println(pathlist);
        
        if(pathlist.isEmpty()){
        System.out.printf("Is empty\n");
        }
        else{  
            populate(pathlist);
        }

    }
     private void populate(List<String> pathlist)
    {
        dm.clear();
        imgsNTextlist.clear();
       
        for(int i=0; i<pathlist.size(); i++){
         dm.addElement(new ImgsNText("", new ImageIcon(pathString+pathlist.get(i))));
         imgsNTextlist.add(new ImgsNText(pathlist.get(i), new ImageIcon(pathString+pathlist.get(i)),623,623));
        }
        
        
        //RENDER IMAGES N TEXT
        jList1.setCellRenderer(new Renderer());
        jList1.setModel(dm);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        lImageSelected = new javax.swing.JLabel();
        lImage3 = new javax.swing.JLabel();
        lImage1 = new javax.swing.JLabel();
        lImage2 = new javax.swing.JLabel();
        lImage9 = new javax.swing.JLabel();
        lImage4 = new javax.swing.JLabel();
        lImage5 = new javax.swing.JLabel();
        lImage6 = new javax.swing.JLabel();
        lImage7 = new javax.swing.JLabel();
        lImage8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lImage10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jComboBox1.setBackground(new java.awt.Color(254, 254, 254));
        jComboBox1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matriz de Coocorrencia", "LBP" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lImageSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/images/Brodatz/D1.gif"))); // NOI18N

        lImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/images/Brodatz/D9.gif"))); // NOI18N

        lImage1.setBackground(new java.awt.Color(254, 254, 254));
        lImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/images/Brodatz/D7.gif"))); // NOI18N

        lImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/images/Brodatz/D11.gif"))); // NOI18N

        lImage9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/images/Brodatz/D4.gif"))); // NOI18N

        lImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/images/Brodatz/D15.gif"))); // NOI18N

        lImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/images/Brodatz/D16.gif"))); // NOI18N

        lImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/images/Brodatz/D13.gif"))); // NOI18N

        lImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/images/Brodatz/D12.gif"))); // NOI18N

        lImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/images/Brodatz/D5.gif"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel3.setText("Extratores");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel4.setText("Distancias");

        jComboBox2.setBackground(new java.awt.Color(254, 254, 254));
        jComboBox2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Euclidiana", "Manhattan" }));

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jButton1.setText("Recuperar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(254, 254, 254));
        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel14.setText("Ângulo");

        jComboBox3.setBackground(new java.awt.Color(254, 254, 254));
        jComboBox3.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "45", "90", "135" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel15.setText("Distância");

        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jButton2.setText("Next >>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lImage10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/images/Brodatz/D10.gif"))); // NOI18N

        jMenuBar1.setAlignmentY(1.0F);
        jMenuBar1.setFont(new java.awt.Font("Monospaced", 0, 64)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(286, 58));

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Open folder");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(1161, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(384, 384, 384))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lImage6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lImage9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lImage10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lImageSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lImageSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lImage3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lImage2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lImage4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lImage5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lImage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lImage9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lImage10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lImage6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex() == 0){
            jLabel15.setVisible(true);
            jLabel14.setVisible(true);
            jLabel3.setVisible(true);
            jComboBox3.setVisible(true);
            jTextField1.setVisible(true);
        }else{
            jLabel3.setVisible(false);
            jLabel15.setVisible(false);
            jLabel14.setVisible(false);
            jComboBox3.setVisible(false);
            jTextField1.setVisible(false);
        }
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(imgList.isEmpty()==false){
        imgList.clear();
        
        } 
       
         MatrizCompare matCom = null;
         position10=0;
        int pos = jList1.getSelectedIndex();
        System.out.println(pos);
        System.out.println(pathString+pathlist.get(pos));
        int distanceChoice = jComboBox2.getSelectedIndex();
        if(jComboBox1.getSelectedItem().toString().compareTo("Matriz de Coocorrencia") ==0){
            System.out.println(imgList.size());
            
            System.out.println("Selecionou matriz de coocorrencia");
            int distancia = Integer.parseInt(jTextField1.getText());
            int angulo =  Integer.parseInt(jComboBox3.getSelectedItem().toString());
            
            
            matCom  = new MatrizCompare(pathString+pathlist.get(pos),distancia, angulo, pathString,pathlist,distanceChoice);
            System.out.println("Criou a matriz!");
            imgList = matCom.CompareImagesMatrizCoocorrencia();
           System.out.println("Criou a lista de imagens mais proximas!");
            System.out.println(imgList);


            setIconImage(lImage1,imgList );
            setIconImage(lImage2,imgList );
            setIconImage(lImage3,imgList );
            setIconImage(lImage4,imgList );
            setIconImage(lImage5,imgList );
            setIconImage(lImage6,imgList );
            setIconImage(lImage7,imgList );
            setIconImage(lImage8,imgList );
            setIconImage(lImage9,imgList );
            setIconImage(lImage10,imgList );
            
        } else if(jComboBox1.getSelectedItem().toString().compareTo("LBP")==0){
            
            System.out.println("Selecionou LBP");
            matCom  = new MatrizCompare(pathString+pathlist.get(pos), pathString,pathlist, distanceChoice);
            System.out.println("Criou a matriz!");
            imgList = matCom.CompareImagesLBP();
           System.out.println("Criou a lista de imagens mais proximas!");


            setIconImage(lImage1,imgList );
            setIconImage(lImage2,imgList );
            setIconImage(lImage3,imgList );
            setIconImage(lImage4,imgList );
            setIconImage(lImage5,imgList );
            setIconImage(lImage6,imgList );
            setIconImage(lImage7,imgList );
            setIconImage(lImage8,imgList );
            setIconImage(lImage9,imgList );
            setIconImage(lImage10,imgList );
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setIconImage(lImage1,imgList );
            setIconImage(lImage2,imgList );
            setIconImage(lImage3,imgList );
            setIconImage(lImage4,imgList );
            setIconImage(lImage5,imgList );
            setIconImage(lImage6,imgList );
            setIconImage(lImage7,imgList );
            setIconImage(lImage8,imgList );
            setIconImage(lImage9,imgList );
            setIconImage(lImage10,imgList );
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         System.out.println("Click");
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
              pathString =  chooser.getSelectedFile().toString() + "/";
              System.out.println(pathString);
              initList();
        }
    else {
      System.out.println("No Selection ");
      }
     //pathString = f.getAbsolutePath();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

public void setIconImage(JLabel label,List<Image> imgList ){
    if(position10 < imgList.size()){
                  label.setIcon(new ImgsNText(imgList.get(position10++)).getImg());
    }else{
                label.setIcon(null);
    }
              
}    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lImage1;
    private javax.swing.JLabel lImage10;
    private javax.swing.JLabel lImage2;
    private javax.swing.JLabel lImage3;
    private javax.swing.JLabel lImage4;
    private javax.swing.JLabel lImage5;
    private javax.swing.JLabel lImage6;
    private javax.swing.JLabel lImage7;
    private javax.swing.JLabel lImage8;
    private javax.swing.JLabel lImage9;
    private javax.swing.JLabel lImageSelected;
    // End of variables declaration//GEN-END:variables
}
